// This file was auto-generated by ML.NET Model Builder. 

using System;
using TestML.Model;

namespace TestML.ConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
            var inputStr = string.Empty;

            // Create single instance of sample data from first line of dataset for model input
          
            Console.WriteLine("Write 0 to exit");

            while (inputStr != "0")
            {
                inputStr = Console.ReadLine();
                ModelInput sampleData = new ModelInput()
                {
                    Col1 = inputStr,
                };
                var predictionResult = ConsumeModel.Predict(sampleData);
                Console.WriteLine("Using model to make single prediction -- Comparing actual Col0 with predicted Col0 from sample data...\n\n");
                Console.WriteLine($"Col1: {sampleData.Col1}");
                Console.WriteLine($"\n\nPredicted Col0 value {predictionResult.Prediction} \nPredicted Col0 scores: [{String.Join(",", predictionResult.Score)}]\n\n");
                Console.WriteLine(predictionResult.Prediction == Convert.ToString(1) ? "This is spam" : "Normal message");
                Console.WriteLine("=============== End of process, hit any key to finish ===============");

            }
                

      
        }
    }
}
