// This file was auto-generated by ML.NET Model Builder. 

using System;
using ConsoleApML.Model;

namespace ConsoleApML.ConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
            var inputStr = string.Empty;

            // Create single instance of sample data from first line of dataset for model input

            Console.WriteLine("Write 0 to exit");
            // Create single instance of sample data from first line of dataset for model input
            while (inputStr != "0")
            {
                inputStr = Console.ReadLine();

               
                    ModelInput sampleData = new ModelInput()
                    {
                        Message = inputStr
                    };

                    // Make a single prediction on the sample data and print results
                    var predictionResult = ConsumeModel.Predict(sampleData);

                    Console.WriteLine("Using model to make single prediction -- Comparing actual Spam with predicted Spam from sample data...\n\n");
                    Console.WriteLine($"Message: {sampleData.Message}");
                    Console.WriteLine($"\n\nPredicted Spam value {predictionResult.Prediction} \nPredicted Spam scores: [{String.Join(",", predictionResult.Score)}]\n\n");
                    Console.WriteLine(predictionResult.Prediction == Convert.ToString(1) ? "This is spam" : "Normal message");

                    Console.ReadKey();
                }
           
                
            }
       
        }
    }

